mods.jei.ingredient.yeet(item('excompressum:auto_hammer'))
mods.jei.ingredient.yeet(item('excompressum:auto_compressed_hammer'))
mods.jei.ingredient.yeet(item('excompressum:auto_sieve'))
mods.jei.ingredient.yeet(item('excompressum:auto_heavy_sieve'))
mods.jei.ingredient.yeet(item('excompressum:auto_compressor'))
mods.jei.ingredient.yeet(item('excompressum:auto_compressor_rationing'))
mods.jei.ingredient.yeet(item('excompressum:compressed_hammer_gold'))
mods.jei.ingredient.yeet(item('excompressum:compressed_hammer_diamond'))
mods.jei.ingredient.yeet(item('excompressum:double_compressed_diamond_hammer'))
mods.jei.ingredient.yeet(item('excompressum:iron_mesh'))
mods.jei.ingredient.yeet(item('excompressum:uncompressed_coal'))
mods.jei.ingredient.yeet(item('excompressum:bat_zapper'))
mods.jei.ingredient.yeet(item('excompressum:ore_smasher'))
mods.jei.ingredient.yeet(item('excompressum:ugly_steel_plating'))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve'))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 1))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 2))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 3))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 4))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 5))
crafting.removeByOutput(item('excompressum:bait', 12))

crafting.addShapeless('parrot_bait', item('excompressum:bait', 12), [ore('dyeYellow'), ore('dyeGreen'), ore('dyeRed')])
